### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by shampooooo** [Linaqruf/dantaggen-cli#1]
Hi, Linaqruf. 

I'm sorry for bringing up something unrelated, but could you tell me why you deleted your Twitter account? I visited Twitter after a long time and was really surprised to find your account gone. :-0

Once I check your response, I will delete my message myself.

**Comment by Linaqruf** [comment]
Hi,

Thank you for your concern. Currently, I'm doing a digital detox and deactivating from any social media such as Twitter and Discord.
